// Demo + self-checks for ds::Trie.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. trie.cpp -o demo && ./demo
//             or:  make run-trie   (from the data_structures/ folder)

#include "trie.hpp"

#include <algorithm>  // std::sort
#include <cassert>
#include <iostream>

int main() {
    std::cout << "=== Trie demo ===\n\n";

    ds::Trie trie;
    const char* words[] = {"cat", "car", "card", "dog", "do", "done"};
    std::cout << "Inserting: ";
    for (const char* w : words) {
        std::cout << w << ' ';
        trie.insert(w);
    }
    std::cout << "\n  word_count=" << trie.word_count() << "\n";

    std::cout << "contains(\"car\")=" << trie.contains("car")
              << "  contains(\"ca\")=" << trie.contains("ca") << "\n";
    std::cout << "starts_with(\"ca\")=" << trie.starts_with("ca")
              << "  starts_with(\"cow\")=" << trie.starts_with("cow") << "\n";

    std::cout << "\nwords_with_prefix(\"ca\"): ";
    auto ca = trie.words_with_prefix("ca");
    for (const auto& w : ca) std::cout << w << ' ';
    std::cout << "\n";

    std::cout << "erase(\"card\") -> " << trie.erase("card")
              << "  word_count=" << trie.word_count() << "\n";

    // ---- self-checks ----
    ds::Trie t;
    t.insert("hello");
    t.insert("hell");
    t.insert("he");
    assert(t.word_count() == 3);
    assert(t.contains("he"));
    assert(t.contains("hell"));
    assert(!t.contains("helicopter"));
    assert(t.starts_with("hel"));
    assert(!t.starts_with("hex"));

    auto hel = t.words_with_prefix("hel");
    assert(hel.size() == 2);
    std::sort(hel.begin(), hel.end());
    assert(hel[0] == "hell" && hel[1] == "hello");

    assert(t.erase("hell"));
    assert(!t.contains("hell"));
    assert(t.contains("hello"));
    assert(t.word_count() == 2);

    assert(!t.erase("missing"));

    ds::Trie copy = t;
    copy.insert("heap");
    assert(copy.word_count() == t.word_count() + 1);
    assert(copy.contains("heap") && !t.contains("heap"));

    t.clear();
    assert(t.empty());
    assert(t.word_count() == 0);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== Trie demo ===

Inserting: cat car card dog do done 
  word_count=6
contains("car")=1  contains("ca")=0
starts_with("ca")=1  starts_with("cow")=0

words_with_prefix("ca"): car card cat 
erase("card") -> 1  word_count=5

All self-checks passed.
 * ============================================================================ */
