/**
 * @file multiset_example.cpp
 * @brief Runnable tour of Multiset<T> — sorted vector with duplicate values.
 *
 * Covers initializer-list construction, insert into duplicate runs, count,
 * find/contains, erase-all copies, and sorted iteration.
 */

#include "multiset/multiset.hpp"
#include <iostream>

// ---------------------------------------------------------------------------
// Section 1: Duplicates are kept; container stores sorted order, not insert order
// ---------------------------------------------------------------------------
void example_initialization() {
    std::cout << "\n=== 1. Initializer list — sorted with duplicates kept ===\n";

    Multiset<int> ms = {3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5};

    std::cout << "Stored (sorted): ";
    for (int x : ms) {
        std::cout << x << ' ';
    }
    std::cout << "\nSize: " << ms.size() << " (all 11 inserts kept)\n";
}

// ---------------------------------------------------------------------------
// Section 2: count — width of the equal_range duplicate run
// ---------------------------------------------------------------------------
void example_count() {
    std::cout << "\n=== 2. count — how many copies of each value ===\n";

    Multiset<int> ms = {3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5};

    std::cout << "count(5) = " << ms.count(5) << "\n";
    std::cout << "count(1) = " << ms.count(1) << "\n";
    std::cout << "count(7) = " << ms.count(7) << "\n";
}

// ---------------------------------------------------------------------------
// Section 3: insert — new copy placed in sorted position with its equals
// ---------------------------------------------------------------------------
void example_insert() {
    std::cout << "\n=== 3. insert — duplicate lands in the equal run ===\n";

    Multiset<int> ms = {1, 3, 3, 5};
    ms.insert(3);

    std::cout << "After insert(3): ";
    for (int x : ms) {
        std::cout << x << ' ';
    }
    std::cout << "\ncount(3) = " << ms.count(3) << "\n";
}

// ---------------------------------------------------------------------------
// Section 4: find and contains — binary search to first matching element
// ---------------------------------------------------------------------------
void example_find() {
    std::cout << "\n=== 4. find / contains ===\n";

    Multiset<int> ms = {10, 20, 20, 30};

    if (ms.contains(20)) {
        auto it = ms.find(20);
        std::cout << "find(20) points to first 20 at value " << *it << "\n";
    }
    std::cout << "contains(99): " << (ms.contains(99) ? "yes" : "no") << "\n";
}

// ---------------------------------------------------------------------------
// Section 5: erase(value) — removes EVERY copy (entire equal_range)
// ---------------------------------------------------------------------------
void example_erase_all() {
    std::cout << "\n=== 5. erase — removes all copies of a value ===\n";

    Multiset<int> ms = {3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5};

    std::cout << "Before erase(5): ";
    for (int x : ms) {
        std::cout << x << ' ';
    }
    std::cout << "\n";

    size_t removed = ms.erase(5);
    std::cout << "erase(5) removed " << removed << " elements\n";

    std::cout << "After: ";
    for (int x : ms) {
        std::cout << x << ' ';
    }
    std::cout << "\n";
}

// ---------------------------------------------------------------------------
// Section 6: clear and empty
// ---------------------------------------------------------------------------
void example_clear() {
    std::cout << "\n=== 6. clear ===\n";

    Multiset<int> ms = {1, 2, 2, 3};
    ms.clear();
    std::cout << "After clear: empty=" << ms.empty() << ", size=" << ms.size() << "\n";
}

int main() {
    std::cout << "=================================================\n";
    std::cout << "       Multiset Class Examples                  \n";
    std::cout << "=================================================\n";

    example_initialization();
    example_count();
    example_insert();
    example_find();
    example_erase_all();
    example_clear();

    std::cout << "\n=================================================\n";
    std::cout << "   All examples completed successfully!        \n";
    std::cout << "=================================================\n";

    return 0;
}

/* ===== EXPECTED OUTPUT (sample run) ============================================
 * Auto-generated by running this program (see tests/README.md).
 * ----------------------------------------------------------------------------
=================================================
       Multiset Class Examples                  
=================================================

=== 1. Initializer list — sorted with duplicates kept ===
Stored (sorted): 1 1 2 3 3 4 5 5 5 6 9 
Size: 11 (all 11 inserts kept)

=== 2. count — how many copies of each value ===
count(5) = 3
count(1) = 2
count(7) = 0

=== 3. insert — duplicate lands in the equal run ===
After insert(3): 1 3 3 3 5 
count(3) = 3

=== 4. find / contains ===
find(20) points to first 20 at value 20
contains(99): no

=== 5. erase — removes all copies of a value ===
Before erase(5): 1 1 2 3 3 4 5 5 5 6 9 
erase(5) removed 3 elements
After: 1 1 2 3 3 4 6 9 

=== 6. clear ===
After clear: empty=1, size=0

=================================================
   All examples completed successfully!        
=================================================
 * ============================================================================ */
