// Demo + self-checks for ds::Stack.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -Istack stack.cpp -o demo && ./demo
//             or:  make run-stack   (from the data_structures/ folder)

#include "stack.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== Stack demo ===\n\n";

    ds::Stack<int> s;
    std::cout << "push 10, 20, 30 (LIFO order on pop):\n";
    s.push(10);
    s.push(20);
    s.push(30);
    std::cout << "  size=" << s.size() << " top=" << s.top() << "\n";

    std::cout << "\npop order: ";
    while (!s.empty()) {
        std::cout << s.top() << ' ';
        s.pop();
    }
    std::cout << "\n";

    ds::Stack<std::string> words;
    words.push("hello");
    words.push("stack");
    std::cout << "\nstring stack top: " << words.top() << "\n";

    // ---- self-checks (assert == silent on success) ----
    ds::Stack<int> a;
    for (int i = 0; i < 50; ++i) a.push(i);
    assert(a.size() == 50);
    assert(a.top() == 49);
    a.pop();
    assert(a.top() == 48);
    assert(a.size() == 49);
    ds::Stack<int> b = a;
    b.push(999);
    assert(b.size() == a.size() + 1);
    assert(b.top() == 999);
    assert(a.top() == 48);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== Stack demo ===

push 10, 20, 30 (LIFO order on pop):
  size=3 top=30

pop order: 30 20 10 

string stack top: stack

All self-checks passed.
 * ============================================================================ */
