// Demo + self-checks for ds::BinaryHeap.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. binary_heap.cpp -o demo && ./demo
//             or:  make run-binary_heap   (from the data_structures/ folder)

#include "binary_heap.hpp"

#include <algorithm>  // std::sort
#include <cassert>
#include <iostream>
#include <vector>

int main() {
    std::cout << "=== BinaryHeap demo (default = MAX-heap) ===\n\n";

    ds::BinaryHeap<int> heap;
    int vals[] = {4, 1, 7, 3, 8, 5};
    std::cout << "Pushing: ";
    for (int v : vals) {
        std::cout << v << ' ';
        heap.push(v);
    }
    std::cout << "\n  top (max)=" << heap.top() << "\n";

    std::cout << "Popping all (descending order): ";
    while (!heap.empty()) {
        std::cout << heap.top() << ' ';
        heap.pop();
    }
    std::cout << "\n";

    std::cout << "\nbuild_heap from unsorted vector:\n";
    std::vector<int> raw = {3, 9, 2, 7, 1, 8, 6};
    auto built = ds::BinaryHeap<int>::build(raw);
    std::cout << "  built top=" << built.top() << " size=" << built.size() << "\n";

    // Heapsort: repeated pop from a max-heap yields ascending sort.
    std::cout << "\nHeapsort demo on {5,3,8,1,9,2}:\n";
    std::vector<int> arr = {5, 3, 8, 1, 9, 2};
    ds::BinaryHeap<int> sorter(arr);
    std::vector<int> sorted;
    while (!sorter.empty()) {
        sorted.push_back(sorter.top());
        sorter.pop();
    }
    std::cout << "  sorted: ";
    for (int x : sorted) std::cout << x << ' ';
    std::cout << "\n";

    // ---- self-checks ----
    ds::BinaryHeap<int> h;
    for (int v : {10, 4, 15, 7, 3}) h.push(v);
    assert(h.top() == 15);
    assert(h.size() == 5);

    h.pop();
    assert(h.top() == 10);
    assert(h.size() == 4);

    std::vector<int> v = {4, 1, 3, 2, 16, 9, 10, 14, 8, 7};
    ds::BinaryHeap<int> b = ds::BinaryHeap<int>::build(v);
    assert(b.top() == 16);
    assert(b.size() == 10);

    std::vector<int> out;
    ds::BinaryHeap<int> copy = b;
    while (!copy.empty()) {
        out.push_back(copy.top());
        copy.pop();
    }
    assert(out[0] == 16);
    for (std::size_t i = 1; i < out.size(); ++i)
        assert(out[i] <= out[i - 1]);  // max-heap pops are non-increasing

    std::vector<int> ascending = out;
    std::sort(ascending.begin(), ascending.end());
    std::vector<int> heap_sorted;
    ds::BinaryHeap<int> hs(v);
    while (!hs.empty()) {
        heap_sorted.insert(heap_sorted.begin(), hs.top());
        hs.pop();
    }
    assert(heap_sorted == ascending);

    ds::BinaryHeap<int, std::greater<int>> min_heap;
    for (int x : {5, 1, 3}) min_heap.push(x);
    assert(min_heap.top() == 1);

    assert(h.empty() == false);
    while (!h.empty()) h.pop();
    assert(h.empty());

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== BinaryHeap demo (default = MAX-heap) ===

Pushing: 4 1 7 3 8 5 
  top (max)=8
Popping all (descending order): 8 7 5 4 3 1 

build_heap from unsorted vector:
  built top=9 size=7

Heapsort demo on {5,3,8,1,9,2}:
  sorted: 9 8 5 3 2 1 

All self-checks passed.
 * ============================================================================ */
