// Demo + self-checks for ds::DoublyLinkedList.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -Idoubly_linked_list doubly_linked_list.cpp -o demo && ./demo
//             or:  make run-doubly_linked_list   (from the data_structures/ folder)

#include "doubly_linked_list.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== DoublyLinkedList demo ===\n\n";

    ds::DoublyLinkedList<int> list;
    std::cout << "push_back 10, 20, 30:\n";
    list.push_back(10);
    list.push_back(20);
    list.push_back(30);
    std::cout << "  front=" << list.front() << " back=" << list.back()
              << " size=" << list.size() << "\n";

    std::cout << "\npush_front(5):\n";
    list.push_front(5);
    std::cout << "  ";
    for (int x : list) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "\npop_front() and pop_back():\n";
    list.pop_front();
    list.pop_back();
    std::cout << "  ";
    for (int x : list) std::cout << x << ' ';
    std::cout << " (size=" << list.size() << ")\n";

    ds::DoublyLinkedList<std::string> words;
    words.push_back("doubly");
    words.push_front("hello");
    std::cout << "\nstring list: front=\"" << words.front()
              << "\" back=\"" << words.back() << "\"\n";

    // ---- self-checks (assert == silent on success) ----
    ds::DoublyLinkedList<int> a;
    a.push_back(1);
    a.push_back(2);
    a.push_front(0);
    assert(a.size() == 3);
    assert(a.front() == 0);
    assert(a.back() == 2);
    a.pop_front();
    assert(a.front() == 1);
    a.pop_back();
    assert(a.back() == 1);
    assert(a.size() == 1);
    ds::DoublyLinkedList<int> b = a;
    b.push_back(9);
    assert(b.size() == a.size() + 1);
    a.clear();
    assert(a.empty());
    assert(b.size() == 2);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== DoublyLinkedList demo ===

push_back 10, 20, 30:
  front=10 back=30 size=3

push_front(5):
  5 10 20 30 

pop_front() and pop_back():
  10 20  (size=2)

string list: front="hello" back="doubly"

All self-checks passed.
 * ============================================================================ */
