/**
 * @file multimap_test.cpp
 * @brief Test suite for the Multimap (sorted-vector of pairs, duplicate keys).
 */

#include "multimap/multimap.hpp"
#include <iostream>
#include <string>

int main() {
    std::cout << "=================================================\n";
    std::cout << "      Multimap Implementation Test Suite        \n";
    std::cout << "=================================================\n\n";

    int passed = 0, total = 10;

    // Test 1: insert allows duplicate keys
    std::cout << "Test 1: duplicate keys... ";
    {
        Multimap<std::string, int> mm;
        mm.insert({"alice", 90});
        mm.insert({"alice", 95});
        mm.insert({"bob", 80});
        if (mm.size() != 3) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 2: count returns number of values for a key
    std::cout << "Test 2: count()... ";
    {
        Multimap<std::string, int> mm = {{"a", 1}, {"a", 2}, {"a", 3}, {"b", 4}};
        if (mm.count("a") != 3 || mm.count("b") != 1 || mm.count("z") != 0) {
            std::cout << "FAILED\n"; return 1;
        }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 3: find returns the first pair with the key
    std::cout << "Test 3: find()... ";
    {
        Multimap<std::string, int> mm = {{"x", 1}, {"y", 2}};
        auto it = mm.find("y");
        if (it == mm.end() || it->second != 2) { std::cout << "FAILED\n"; return 1; }
        if (mm.find("nope") != mm.end()) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 4: iteration is ordered by key
    std::cout << "Test 4: key-ordered iteration... ";
    {
        Multimap<int, int> mm = {{3, 0}, {1, 0}, {2, 0}, {1, 0}};
        int prev = -1; bool sorted = true;
        for (const auto& kv : mm) { if (kv.first < prev) sorted = false; prev = kv.first; }
        if (!sorted) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 5: erase removes ALL values for the key
    std::cout << "Test 5: erase whole key block... ";
    {
        Multimap<std::string, int> mm = {{"a", 1}, {"a", 2}, {"a", 3}, {"b", 4}};
        auto n = mm.erase("a");
        if (n != 3 || mm.count("a") != 0 || mm.size() != 1) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 6: erase absent key returns 0
    std::cout << "Test 6: erase absent... ";
    {
        Multimap<int, int> mm = {{1, 1}};
        if (mm.erase(99) != 0 || mm.size() != 1) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 7: contains
    std::cout << "Test 7: contains()... ";
    {
        Multimap<std::string, int> mm = {{"k", 1}};
        if (!mm.contains("k") || mm.contains("missing")) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 8: empty / clear
    std::cout << "Test 8: empty/clear... ";
    {
        Multimap<int, int> mm = {{1, 1}, {2, 2}};
        if (mm.empty()) { std::cout << "FAILED\n"; return 1; }
        mm.clear();
        if (!mm.empty() || mm.size() != 0) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 9: all values for a duplicated key are retrievable by scanning
    std::cout << "Test 9: duplicate values present... ";
    {
        Multimap<std::string, int> mm = {{"a", 90}, {"a", 95}, {"a", 99}};
        int sum = 0, n = 0;
        for (const auto& kv : mm) if (kv.first == "a") { sum += kv.second; ++n; }
        if (n != 3 || sum != 90 + 95 + 99) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    // Test 10: init-list construction with duplicate keys
    std::cout << "Test 10: init-list construction... ";
    {
        Multimap<int, char> mm = {{1, 'a'}, {1, 'b'}, {2, 'c'}};
        if (mm.size() != 3 || mm.count(1) != 2) { std::cout << "FAILED\n"; return 1; }
    }
    std::cout << "PASSED\n"; ++passed;

    std::cout << "\n=================================================\n";
    std::cout << "  RESULTS: " << passed << "/" << total << " tests passed\n";
    std::cout << "=================================================\n";
    if (passed == total) { std::cout << "\xE2\x9C\x93 All tests PASSED!\n"; return 0; }
    std::cout << "\xE2\x9C\x97 Some tests FAILED\n";
    return 1;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this program (see tests/README.md).
 * ----------------------------------------------------------------------------
=================================================
      Multimap Implementation Test Suite        
=================================================

Test 1: duplicate keys... PASSED
Test 2: count()... PASSED
Test 3: find()... PASSED
Test 4: key-ordered iteration... PASSED
Test 5: erase whole key block... PASSED
Test 6: erase absent... PASSED
Test 7: contains()... PASSED
Test 8: empty/clear... PASSED
Test 9: duplicate values present... PASSED
Test 10: init-list construction... PASSED

=================================================
  RESULTS: 10/10 tests passed
=================================================
✓ All tests PASSED!
 * ============================================================================ */
