// Demo + self-checks for ds::Queue.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -Iqueue queue.cpp -o demo && ./demo
//             or:  make run-queue   (from the data_structures/ folder)

#include "queue.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== Queue demo ===\n\n";

    ds::Queue<int> q;
    std::cout << "enqueue 10, 20, 30 (FIFO order on dequeue):\n";
    q.enqueue(10);
    q.enqueue(20);
    q.enqueue(30);
    std::cout << "  size=" << q.size() << " front=" << q.front() << "\n";

    std::cout << "\ndequeue order: ";
    while (!q.empty()) {
        std::cout << q.front() << ' ';
        q.dequeue();
    }
    std::cout << "\n";

    std::cout << "\nwraparound test (enqueue/dequeue many):\n";
    for (int i = 0; i < 10; ++i) q.enqueue(i);
    for (int i = 0; i < 5; ++i) q.dequeue();
    for (int i = 10; i < 15; ++i) q.enqueue(i);
    std::cout << "  front=" << q.front() << " size=" << q.size() << "\n";

    ds::Queue<std::string> words;
    words.enqueue("first");
    words.enqueue("second");
    std::cout << "\nstring queue front: " << words.front() << "\n";

    // ---- self-checks (assert == silent on success) ----
    ds::Queue<int> a;
    for (int i = 0; i < 100; ++i) a.enqueue(i);
    assert(a.size() == 100);
    assert(a.front() == 0);
    a.dequeue();
    assert(a.front() == 1);
    assert(a.size() == 99);
    for (int i = 0; i < 50; ++i) a.dequeue();
    assert(a.front() == 51);
    ds::Queue<int> b = a;
    b.enqueue(999);
    assert(b.size() == a.size() + 1);
    assert(a.front() == 51);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== Queue demo ===

enqueue 10, 20, 30 (FIFO order on dequeue):
  size=3 front=10

dequeue order: 10 20 30 

wraparound test (enqueue/dequeue many):
  front=5 size=10

string queue front: first

All self-checks passed.
 * ============================================================================ */
