// Demo + self-checks for ds::Graph.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. graph.cpp -o demo && ./demo
//             or:  make run-graph   (from the data_structures/ folder)

#include "graph.hpp"

#include <cassert>
#include <climits>
#include <iostream>
#include <string>

static void print_order(const std::string& label, const std::vector<int>& v) {
    std::cout << label << ": ";
    for (int x : v) std::cout << x << ' ';
    std::cout << '\n';
}

int main() {
    std::cout << "=== Graph demo ===\n\n";

    // Small directed weighted graph (vertices 0..4)
    //
    //   0 --4--> 1 --1--> 3
    //   |        |
    //   1        2
    //   v        v
    //   2        4
    //
    ds::Graph g(5, true);
    g.add_edge(0, 1, 4);
    g.add_edge(0, 2, 1);
    g.add_edge(1, 3, 1);
    g.add_edge(1, 4, 2);
    g.add_edge(2, 4, 5);

    std::cout << "Directed graph, 5 vertices\n";
    print_order("BFS from 0", g.bfs(0));
    print_order("DFS from 0", g.dfs(0));

    std::cout << "\nDijkstra distances from 0:\n";
    std::vector<int> dist = g.dijkstra(0);
    for (int v = 0; v < 5; ++v)
        std::cout << "  to " << v << ": " << dist[static_cast<std::size_t>(v)] << '\n';

    // DAG for topological sort: 5 -> 0, 5 -> 2, ...
    ds::Graph dag(6, true);
    dag.add_edge(5, 2);
    dag.add_edge(5, 0);
    dag.add_edge(4, 0);
    dag.add_edge(4, 1);
    dag.add_edge(2, 3);
    dag.add_edge(3, 1);

    std::vector<int> topo = dag.topological_sort();
    std::cout << "\nTopological order (Kahn): ";
    for (int v : topo) std::cout << v << ' ';
    std::cout << '\n';

    // Undirected snippet
    ds::Graph ug(3, false);
    ug.add_edge(0, 1);
    ug.add_edge(1, 2);
    std::cout << "\nUndirected: neighbors(1) -> ";
    for (const ds::Edge& e : ug.neighbors(1))
        std::cout << e.to << "(w=" << e.weight << ") ";
    std::cout << '\n';

    // ---- self-checks (assert == silent on success) ----
    ds::Graph t(4, true);
    t.add_edge(0, 1);
    t.add_edge(0, 2);
    t.add_edge(1, 3);
    t.add_edge(2, 3);

    std::vector<int> b = t.bfs(0);
    assert(b.size() == 4);
    assert(b[0] == 0);
    assert(b[1] == 1);
    assert(b[2] == 2);
    assert(b[3] == 3);

    std::vector<int> d = t.dfs(0);
    assert(d.size() == 4);
    assert(d[0] == 0);

    ds::Graph w(4, true);
    w.add_edge(0, 1, 10);
    w.add_edge(0, 2, 1);
    w.add_edge(2, 1, 1);
    w.add_edge(1, 3, 1);
    std::vector<int> wd = w.dijkstra(0);
    assert(wd[3] == 3);   // 0 -> 2 -> 1 -> 3

    ds::Graph cyclic(3, true);
    cyclic.add_edge(0, 1);
    cyclic.add_edge(1, 2);
    cyclic.add_edge(2, 0);
    assert(cyclic.topological_sort().empty());  // cycle

    ds::Graph chain(3, true);
    chain.add_edge(0, 1);
    chain.add_edge(1, 2);
    std::vector<int> ts = chain.topological_sort();
    assert(ts.size() == 3);
    assert(ts[0] == 0 && ts[1] == 1 && ts[2] == 2);

    ds::Graph und(2, false);
    und.add_edge(0, 1, 7);
    assert(und.neighbors(0).size() == 1);
    assert(und.neighbors(1).size() == 1);
    assert(und.neighbors(0)[0].weight == 7);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== Graph demo ===

Directed graph, 5 vertices
BFS from 0: 0 1 2 3 4 
DFS from 0: 0 1 3 4 2 

Dijkstra distances from 0:
  to 0: 0
  to 1: 4
  to 2: 1
  to 3: 5
  to 4: 6

Topological order (Kahn): 4 5 2 0 3 1 

Undirected: neighbors(1) -> 0(w=1) 2(w=1) 

All self-checks passed.
 * ============================================================================ */
