// Demo + self-checks for ds::DisjointSet.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. union_find.cpp -o demo && ./demo
//             or:  make run-union_find   (from the data_structures/ folder)

#include "union_find.hpp"

#include <cassert>
#include <iostream>

int main() {
    std::cout << "=== DisjointSet (Union-Find) demo ===\n\n";

    ds::DisjointSet uf(6);
    std::cout << "Start: " << uf.count() << " sets over 6 elements\n";

    std::cout << "unite(0, 1), unite(2, 3), unite(1, 2):\n";
    uf.unite(0, 1);
    uf.unite(2, 3);
    uf.unite(1, 2);
    std::cout << "  count=" << uf.count()
              << "  connected(0,3)=" << (uf.connected(0, 3) ? "yes" : "no")
              << "  connected(0,4)=" << (uf.connected(0, 4) ? "yes" : "no")
              << '\n';

    std::cout << "unite(4, 5):\n";
    uf.unite(4, 5);
    std::cout << "  count=" << uf.count()
              << "  find(5)=" << uf.find(5) << '\n';

    std::cout << "\nPath compression: repeated find(3) flattens {0,1,2,3}\n";
    std::cout << "  find(3)=" << uf.find(3) << '\n';

    // ---- self-checks (assert == silent on success) ----
    ds::DisjointSet a(5);
    assert(a.count() == 5);
    assert(!a.connected(0, 1));

    a.unite(0, 1);
    assert(a.count() == 4);
    assert(a.connected(0, 1));
    assert(a.find(0) == a.find(1));

    a.unite(2, 3);
    a.unite(1, 2);
    assert(a.count() == 2);
    assert(a.connected(0, 3));
    assert(!a.connected(0, 4));

    a.unite(0, 0);  // same set — no change
    assert(a.count() == 2);

    // Stress: many unions on a larger set
    ds::DisjointSet big(100);
    for (int i = 0; i < 99; ++i) big.unite(i, i + 1);
    assert(big.count() == 1);
    assert(big.connected(0, 99));
    assert(big.find(50) == big.find(0));

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== DisjointSet (Union-Find) demo ===

Start: 6 sets over 6 elements
unite(0, 1), unite(2, 3), unite(1, 2):
  count=3  connected(0,3)=yes  connected(0,4)=no
unite(4, 5):
  count=2  find(5)=4

Path compression: repeated find(3) flattens {0,1,2,3}
  find(3)=0

All self-checks passed.
 * ============================================================================ */
