// Demo + self-checks for ds::HashTable.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. hash_table.cpp -o demo && ./demo
//             or:  make run-hash_table   (from the data_structures/ folder)

#include "hash_table.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== HashTable demo ===\n\n";

    ds::HashTable<std::string, int> ages;
    ages.put("alice", 20);
    ages.put("bob", 22);
    ages.put("carol", 19);
    std::cout << "After 3 puts: size=" << ages.size()
              << " buckets=" << ages.bucket_count()
              << " load=" << ages.load_factor() << "\n";

    std::cout << "get(\"bob\") -> " << *ages.get("bob") << "\n";
    std::cout << "contains(\"dave\") -> " << (ages.contains("dave") ? "yes" : "no") << "\n";

    std::cout << "\nUpdate alice to 21:\n";
    ages.put("alice", 21);
    std::cout << "  alice=" << *ages.get("alice") << "\n";

    std::cout << "\nErase bob:\n";
    ages.erase("bob");
    std::cout << "  size=" << ages.size()
              << " contains(bob)=" << (ages.contains("bob") ? "yes" : "no") << "\n";

    // Force rehash by inserting many keys
    std::cout << "\nInserting 20 more names to trigger rehash:\n";
    std::size_t buckets_before = ages.bucket_count();
    for (int i = 0; i < 20; ++i)
        ages.put("user" + std::to_string(i), i);
    std::cout << "  buckets " << buckets_before << " -> " << ages.bucket_count()
              << "  load=" << ages.load_factor() << "\n";

    // ---- self-checks (assert == silent on success) ----
    ds::HashTable<int, std::string> m;
    m.put(1, "one");
    m.put(2, "two");
    m.put(1, "ONE");                    // update
    assert(m.size() == 2);
    assert(*m.get(1) == "ONE");
    assert(m.contains(2));
    assert(!m.contains(99));
    assert(m.get(99) == nullptr);
    assert(m.erase(2));
    assert(!m.erase(2));                // already gone
    assert(m.size() == 1);
    assert(m.empty() == false);
    m.clear();
    assert(m.empty());

    // Rehash: start small, insert until bucket count grows
    ds::HashTable<int, int> small(4, 0.75);
    std::size_t b0 = small.bucket_count();
    for (int i = 0; i < 10; ++i) small.put(i, i * 10);
    assert(small.bucket_count() > b0);
    assert(small.size() == 10);
    for (int i = 0; i < 10; ++i)
        assert(*small.get(i) == i * 10);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== HashTable demo ===

After 3 puts: size=3 buckets=8 load=0.375
get("bob") -> 22
contains("dave") -> no

Update alice to 21:
  alice=21

Erase bob:
  size=2 contains(bob)=no

Inserting 20 more names to trigger rehash:
  buckets 8 -> 32  load=0.6875

All self-checks passed.
 * ============================================================================ */
