// Demo + self-checks for ds::BST.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. binary_search_tree.cpp -o demo && ./demo
//             or:  make run-binary_search_tree   (from the data_structures/ folder)

#include "binary_search_tree.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== BST demo ===\n\n";

    ds::BST<int> tree;
    int keys[] = {8, 3, 10, 1, 6, 14, 4, 7, 13};
    std::cout << "Inserting: ";
    for (int k : keys) {
        std::cout << k << ' ';
        tree.insert(k);
    }
    std::cout << "\n  size=" << tree.size() << " height=" << tree.height() << "\n";

    std::cout << "min=" << tree.min() << " max=" << tree.max() << "\n";

    std::cout << "In-order: ";
    auto sorted = tree.in_order();
    for (int x : sorted) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "\ncontains(6)=" << tree.contains(6)
              << "  contains(99)=" << tree.contains(99) << "\n";

    std::cout << "\nErase leaf (1), one-child splice would be (none here), two-child (10):\n";
    tree.erase(1);
    tree.erase(10);
    std::cout << "  after erase: ";
    for (int x : tree.in_order()) std::cout << x << ' ';
    std::cout << "  size=" << tree.size() << "\n";

    // ---- self-checks ----
    ds::BST<int> t;
    for (int k : {5, 2, 8, 1, 9}) t.insert(k);
    assert(t.size() == 5);
    assert(t.contains(8));
    assert(!t.contains(7));
    assert(t.min() == 1);
    assert(t.max() == 9);

    auto v = t.in_order();
    assert(v.size() == 5);
    assert(v[0] == 1 && v[4] == 9);

    assert(t.erase(1));   // leaf
    assert(t.size() == 4);
    assert(!t.contains(1));

    assert(t.erase(2));   // one child (left child 5 or right — 2 has no right)
    assert(t.size() == 3);

    assert(t.erase(5));   // two children (successor 8)
    assert(t.size() == 2);
    assert(t.contains(8) && t.contains(9));

    ds::BST<int> copy = t;
    copy.insert(0);
    assert(copy.size() == t.size() + 1);
    assert(copy.contains(0) && !t.contains(0));

    t.clear();
    assert(t.empty());
    assert(t.height() == 0);

    ds::BST<std::string> words;
    words.insert("cat");
    words.insert("dog");
    assert(words.contains("cat"));
    auto w = words.in_order();
    assert(w[0] == "cat");

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== BST demo ===

Inserting: 8 3 10 1 6 14 4 7 13 
  size=9 height=4
min=1 max=14
In-order: 1 3 4 6 7 8 10 13 14 

contains(6)=1  contains(99)=0

Erase leaf (1), one-child splice would be (none here), two-child (10):
  after erase: 3 4 6 7 8 13 14   size=7

All self-checks passed.
 * ============================================================================ */
