// Demo + self-checks for ds::AVLTree.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. avl_tree.cpp -o demo && ./demo
//             or:  make run-avl_tree   (from the data_structures/ folder)

#include "avl_tree.hpp"

#include <cassert>
#include <iostream>

int main() {
    std::cout << "=== AVLTree demo ===\n\n";

    ds::AVLTree<int> tree;

    // Sorted insert would skew a plain BST; AVL stays balanced.
    std::cout << "Inserting 1..15 in order (AVL rebalances):\n";
    for (int i = 1; i <= 15; ++i) tree.insert(i);
    std::cout << "  size=" << tree.size() << " height=" << tree.height() << "\n";
    std::cout << "  (plain BST would have height 15)\n";

    std::cout << "In-order: ";
    for (int x : tree.in_order()) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "\nInsert triggers LR case: insert 20 then 18 into {10,15,25}:\n";
    ds::AVLTree<int> lr;
    for (int k : {10, 15, 25}) lr.insert(k);
    lr.insert(20);
    lr.insert(18);
    std::cout << "  height=" << lr.height() << " in-order: ";
    for (int x : lr.in_order()) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "contains(7)=" << tree.contains(7)
              << "  erase(7)=" << tree.erase(7) << "\n";

    // ---- self-checks ----
    ds::AVLTree<int> t;
    for (int i = 1; i <= 31; ++i) t.insert(i);
    assert(t.size() == 31);
    assert(t.height() <= 6);  // AVL height bound ~ 1.44 log2(N)

    for (int i = 1; i <= 31; ++i) assert(t.contains(i));

    auto sorted = t.in_order();
    for (std::size_t i = 0; i < sorted.size(); ++i)
        assert(sorted[i] == static_cast<int>(i + 1));

    // LL case: insert 30, 20, 10
    ds::AVLTree<int> ll;
    for (int k : {30, 20, 10}) ll.insert(k);
    assert(ll.height() == 2);
    assert(ll.contains(20));

    // RR case: insert 10, 20, 30
    ds::AVLTree<int> rr;
    for (int k : {10, 20, 30}) rr.insert(k);
    assert(rr.height() == 2);

    // RL case
    ds::AVLTree<int> rl;
    for (int k : {10, 30, 20}) rl.insert(k);
    assert(rl.height() == 2);

    assert(t.erase(16));
    assert(!t.contains(16));
    assert(t.size() == 30);

    ds::AVLTree<int> copy = t;
    copy.insert(0);
    assert(copy.size() == t.size() + 1);

    t.clear();
    assert(t.empty());

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== AVLTree demo ===

Inserting 1..15 in order (AVL rebalances):
  size=15 height=4
  (plain BST would have height 15)
In-order: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

Insert triggers LR case: insert 20 then 18 into {10,15,25}:
  height=3 in-order: 10 15 18 20 25 
contains(7)=1  erase(7)=1

All self-checks passed.
 * ============================================================================ */
