// Demo + self-checks for ds::Deque.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -Ideque deque.cpp -o demo && ./demo
//             or:  make run-deque   (from the data_structures/ folder)

#include "deque.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== Deque demo ===\n\n";

    ds::Deque<int> d;
    std::cout << "push_back 10, 20, 30:\n";
    d.push_back(10);
    d.push_back(20);
    d.push_back(30);
    std::cout << "  front=" << d.front() << " back=" << d.back()
              << " size=" << d.size() << "\n";

    std::cout << "\npush_front(5) and push_front(1):\n";
    d.push_front(5);
    d.push_front(1);
    std::cout << "  ";
    for (std::size_t i = 0; i < d.size(); ++i) std::cout << d[i] << ' ';
    std::cout << "\n";

    std::cout << "\npop_front() and pop_back():\n";
    d.pop_front();
    d.pop_back();
    std::cout << "  front=" << d.front() << " back=" << d.back()
              << " size=" << d.size() << "\n";

    std::cout << "\nwraparound (many push/pop at both ends):\n";
    ds::Deque<int> ring;
    for (int i = 0; i < 8; ++i) ring.push_back(i);
    ring.pop_front();
    ring.pop_front();
    ring.push_front(-1);
    ring.push_front(-2);
    ring.push_back(99);
    std::cout << "  front=" << ring.front() << " back=" << ring.back()
              << " [0]=" << ring[0] << " [size-1]=" << ring[ring.size() - 1] << "\n";

    ds::Deque<std::string> words;
    words.push_back("world");
    words.push_front("hello");
    std::cout << "\nstring deque: front=\"" << words.front()
              << "\" back=\"" << words.back() << "\"\n";

    // ---- self-checks (assert == silent on success) ----
    ds::Deque<int> a;
    a.push_back(1);
    a.push_back(2);
    a.push_front(0);
    assert(a.size() == 3);
    assert(a.front() == 0);
    assert(a.back() == 2);
    assert(a[1] == 1);
    a.pop_front();
    assert(a.front() == 1);
    a.pop_back();
    assert(a.back() == 1);
    assert(a.size() == 1);
    for (int i = 0; i < 100; ++i) a.push_back(i);
    assert(a.size() == 101);
    assert(a[0] == 1);
    assert(a[100] == 99);
    ds::Deque<int> b = a;
    b.push_front(-1);
    assert(b.size() == a.size() + 1);
    assert(b.front() == -1);
    assert(a.front() == 1);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== Deque demo ===

push_back 10, 20, 30:
  front=10 back=30 size=3

push_front(5) and push_front(1):
  1 5 10 20 30 

pop_front() and pop_back():
  front=5 back=20 size=3

wraparound (many push/pop at both ends):
  front=-2 back=99 [0]=-2 [size-1]=99

string deque: front="hello" back="world"

All self-checks passed.
 * ============================================================================ */
