// Demo + self-checks for ds::LRUCache.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. lru_cache.cpp -o demo && ./demo
//             or:  make run-lru_cache   (from the data_structures/ folder)

#include "lru_cache.hpp"

#include <cassert>
#include <iostream>
#include <string>

// Print the cache contents from MRU (front) to LRU (back).
template <typename K, typename V>
static void dump(const ds::LRUCache<K, V>& c, const char* label) {
    std::cout << label << " [MRU..LRU]: ";
    c.for_each_mru_to_lru([](const K& k, const V& v) {
        std::cout << k << "=" << v << " ";
    });
    std::cout << "(size " << c.size() << "/" << c.capacity() << ")\n";
}

int main() {
    std::cout << "=== LRUCache demo ===\n\n";

    ds::LRUCache<std::string, int> cache(3);

    std::cout << "put A=10, B=20, C=30 (capacity 3):\n";
    cache.put("A", 10);
    cache.put("B", 20);
    cache.put("C", 30);
    dump(cache, "  ");

    std::cout << "\nget(A) -> promotes A to MRU:\n";
    std::cout << "  A = " << *cache.get("A") << "\n";
    dump(cache, "  ");

    std::cout << "\nput D=40 -> cache full, evicts LRU (B):\n";
    cache.put("D", 40);
    dump(cache, "  ");
    std::cout << "  contains(B)? " << (cache.contains("B") ? "yes" : "no") << "\n";

    std::cout << "\nget(B) after eviction -> miss:\n";
    std::cout << "  get(B) returns nullptr: " << (cache.get("B") == nullptr ? "yes" : "no") << "\n";

    std::cout << "\nput C=99 -> updates existing key, promotes to MRU:\n";
    cache.put("C", 99);
    dump(cache, "  ");

    std::cout << "\nerase(D):\n";
    cache.erase("D");
    dump(cache, "  ");

    // ---- self-checks (assert == silent on success) ----
    ds::LRUCache<int, int> lru(2);
    lru.put(1, 1);
    lru.put(2, 2);
    assert(*lru.get(1) == 1);     // 1 is now MRU, 2 is LRU
    lru.put(3, 3);                // evicts key 2
    assert(lru.get(2) == nullptr);
    assert(lru.contains(1) && lru.contains(3));
    assert(lru.size() == 2);

    lru.put(4, 4);                // evicts key 1 (LRU after 3 inserted)
    assert(lru.get(1) == nullptr);
    assert(*lru.get(3) == 3);
    assert(*lru.get(4) == 4);

    // update refreshes value + recency, never grows past capacity
    lru.put(3, 33);
    assert(*lru.get(3) == 33);
    assert(lru.size() == 2);
    assert(lru.most_recent() == 3);

    // capacity 0 is rejected
    bool threw = false;
    try { ds::LRUCache<int, int> bad(0); } catch (const std::invalid_argument&) { threw = true; }
    assert(threw);

    // erase + clear
    assert(lru.erase(4));
    assert(!lru.erase(4));        // already gone
    lru.clear();
    assert(lru.empty());

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== LRUCache demo ===

put A=10, B=20, C=30 (capacity 3):
   [MRU..LRU]: C=30 B=20 A=10 (size 3/3)

get(A) -> promotes A to MRU:
  A = 10
   [MRU..LRU]: A=10 C=30 B=20 (size 3/3)

put D=40 -> cache full, evicts LRU (B):
   [MRU..LRU]: D=40 A=10 C=30 (size 3/3)
  contains(B)? no

get(B) after eviction -> miss:
  get(B) returns nullptr: yes

put C=99 -> updates existing key, promotes to MRU:
   [MRU..LRU]: C=99 D=40 A=10 (size 3/3)

erase(D):
   [MRU..LRU]: C=99 A=10 (size 2/3)

All self-checks passed.
 * ============================================================================ */

