// Demo + self-checks for ds::SinglyLinkedList.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -Isingly_linked_list singly_linked_list.cpp -o demo && ./demo
//             or:  make run-singly_linked_list   (from the data_structures/ folder)

#include "singly_linked_list.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== SinglyLinkedList demo ===\n\n";

    ds::SinglyLinkedList<int> list;
    std::cout << "push_back 10, 20, 30:\n";
    list.push_back(10);
    list.push_back(20);
    list.push_back(30);
    std::cout << "  size=" << list.size() << " front=" << list.front() << "\n";

    std::cout << "\npush_front(5):\n";
    list.push_front(5);
    std::cout << "  ";
    for (int x : list) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "\nfind(20): " << (list.find(20) ? "yes" : "no") << "\n";
    std::cout << "find(99): " << (list.find(99) ? "yes" : "no") << "\n";

    std::cout << "\nremove(20):\n";
    list.remove(20);
    std::cout << "  ";
    for (int x : list) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "\nreverse():\n";
    list.reverse();
    std::cout << "  ";
    for (int x : list) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "\npop_front() twice:\n";
    list.pop_front();
    list.pop_front();
    std::cout << "  size=" << list.size() << " empty=" << list.empty() << "\n";

    ds::SinglyLinkedList<std::string> words;
    words.push_back("linked");
    words.push_back("list");
    std::cout << "\nstring list: " << words.front() << " ... size=" << words.size() << "\n";

    // ---- self-checks (assert == silent on success) ----
    ds::SinglyLinkedList<int> a;
    a.push_back(1);
    a.push_back(2);
    a.push_back(3);
    assert(a.size() == 3);
    assert(a.front() == 1);
    a.push_front(0);
    assert(a.front() == 0);
    assert(a.find(2));
    assert(!a.find(9));
    a.remove(2);
    assert(a.size() == 3);
    assert(!a.find(2));
    a.reverse();
    assert(a.front() == 3);
    ds::SinglyLinkedList<int> b = a;
    b.push_back(99);
    assert(b.size() == a.size() + 1);
    a.clear();
    assert(a.empty());
    assert(b.size() == 4);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== SinglyLinkedList demo ===

push_back 10, 20, 30:
  size=3 front=10

push_front(5):
  5 10 20 30 

find(20): yes
find(99): no

remove(20):
  5 10 30 

reverse():
  30 10 5 

pop_front() twice:
  size=1 empty=0

string list: linked ... size=2

All self-checks passed.
 * ============================================================================ */
