// Demo + self-checks for ds::DynamicArray.
//
//   build & run:  g++ -std=c++14 -Wall -Wextra -I.. dynamic_array.cpp -o demo && ./demo
//             or:  make run-dynamic_array   (from the data_structures/ folder)

#include "dynamic_array.hpp"

#include <cassert>
#include <iostream>
#include <string>

int main() {
    std::cout << "=== DynamicArray demo ===\n\n";

    ds::DynamicArray<int> a;
    std::cout << "Pushing 1..6, watching capacity double:\n";
    for (int i = 1; i <= 6; ++i) {
        a.push_back(i);
        std::cout << "  size=" << a.size() << " capacity=" << a.capacity() << "\n";
    }

    std::cout << "\nContents: ";
    for (int x : a) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "front=" << a.front() << " back=" << a.back()
              << " a[2]=" << a[2] << "\n";

    std::cout << "\ninsert(0, 99) and insert(3, 77):\n";
    a.insert(0, 99);
    a.insert(3, 77);
    std::cout << "  ";
    for (int x : a) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "erase(3) and pop_back():\n";
    a.erase(3);
    a.pop_back();
    std::cout << "  ";
    for (int x : a) std::cout << x << ' ';
    std::cout << "\n";

    std::cout << "\nfind(4) -> index " << a.find(4) << "\n";
    std::cout << "find(123) -> index " << a.find(123) << " (== size, not found)\n";

    // at() bounds checking
    bool threw = false;
    try { a.at(999); } catch (const std::out_of_range&) { threw = true; }
    std::cout << "at(999) threw out_of_range: " << (threw ? "yes" : "no") << "\n";

    // works with any type
    ds::DynamicArray<std::string> words;
    words.push_back("data");
    words.push_back("structures");
    std::cout << "\nstring array: " << words[0] << ' ' << words[1] << "\n";

    // ---- self-checks (assert == silent on success) ----
    ds::DynamicArray<int> b;
    for (int i = 0; i < 100; ++i) b.push_back(i * i);
    assert(b.size() == 100);
    assert(b[99] == 99 * 99);
    assert(b.find(81) == 9);
    b.erase(0);
    assert(b.front() == 1);
    b.insert(0, -1);
    assert(b.front() == -1);
    ds::DynamicArray<int> c = b;           // deep copy
    c.push_back(7);
    assert(c.size() == b.size() + 1);      // independent
    assert(threw);

    std::cout << "\nAll self-checks passed.\n";
    return 0;
}

/* ===== EXPECTED OUTPUT ============================================
 * Auto-generated by running this demo (see data_structures/README.md).
 * ----------------------------------------------------------------------------
=== DynamicArray demo ===

Pushing 1..6, watching capacity double:
  size=1 capacity=1
  size=2 capacity=2
  size=3 capacity=4
  size=4 capacity=4
  size=5 capacity=8
  size=6 capacity=8

Contents: 1 2 3 4 5 6 
front=1 back=6 a[2]=3

insert(0, 99) and insert(3, 77):
  99 1 2 77 3 4 5 6 
erase(3) and pop_back():
  99 1 2 3 4 5 

find(4) -> index 4
find(123) -> index 6 (== size, not found)
at(999) threw out_of_range: yes

string array: data structures

All self-checks passed.
 * ============================================================================ */
