/**
 * @file unordered_set_example.cpp
 * @brief Runnable tour of UnorderedSet — hash table, chains, rehash, and membership.
 *
 * Demonstrates: construction from initializer_list (duplicates dropped), insert/erase,
 * contains/count, clear, and string keys. Order of elements is unspecified.
 */

#include "unordered_set/unordered_set.hpp"
#include <iostream>
#include <string>

int main() {
    std::cout << "=== UnorderedSet Examples ===\n\n";

    // -------------------------------------------------------------------------
    // Section 1: Initializer list — duplicates are silently rejected
    // -------------------------------------------------------------------------
    std::cout << "--- 1. Construction and duplicates ---\n";
    UnorderedSet<int> us = {3, 1, 4, 1, 5, 9, 2, 6};
    std::cout << "Inserted {3,1,4,1,5,9,2,6} → size " << us.size()
              << " (duplicate 1 removed)\n";

    // -------------------------------------------------------------------------
    // Section 2: Membership — hash to bucket, walk chain
    // -------------------------------------------------------------------------
    std::cout << "\n--- 2. contains / count ---\n";
    std::cout << "contains(5): " << (us.contains(5) ? "yes" : "no") << "\n";
    std::cout << "contains(99): " << (us.contains(99) ? "yes" : "no") << "\n";
    std::cout << "count(4): " << us.count(4) << "  count(1): " << us.count(1) << "\n";

    // -------------------------------------------------------------------------
    // Section 3: insert returns false on duplicate; erase removes one node
    // -------------------------------------------------------------------------
    std::cout << "\n--- 3. insert and erase ---\n";
    std::cout << "insert(10): " << (us.insert(10) ? "added" : "rejected") << "\n";
    std::cout << "insert(5):  " << (us.insert(5) ? "added" : "rejected (duplicate)") << "\n";
    us.erase(3);
    std::cout << "After erase(3): size=" << us.size()
              << ", contains(3)=" << (us.contains(3) ? "yes" : "no")
              << ", contains(10)=" << (us.contains(10) ? "yes" : "no") << "\n";

    // -------------------------------------------------------------------------
    // Section 4: String keys — std::hash<std::string> drives bucket index
    // -------------------------------------------------------------------------
    std::cout << "\n--- 4. UnorderedSet<string> ---\n";
    UnorderedSet<std::string> words = {"apple", "banana", "cherry"};
    words.insert("date");
    std::cout << "Word set size: " << words.size() << "\n";
    std::cout << "contains(\"banana\"): " << (words.contains("banana") ? "yes" : "no") << "\n";
    std::cout << "erase(\"banana\"): removed " << words.erase("banana") << " element(s)\n";

    // -------------------------------------------------------------------------
    // Section 5: clear — empty all chains; bucket count unchanged
    // -------------------------------------------------------------------------
    std::cout << "\n--- 5. clear ---\n";
    std::cout << "Before clear: empty=" << words.empty() << " size=" << words.size() << "\n";
    words.clear();
    std::cout << "After clear:  empty=" << words.empty() << " size=" << words.size() << "\n";

    std::cout << "\n✓ Examples completed!\n";
    return 0;
}

/* ===== EXPECTED OUTPUT (sample run) ============================================
 * Auto-generated by running this program (see tests/README.md).
 * ----------------------------------------------------------------------------
=== UnorderedSet Examples ===

--- 1. Construction and duplicates ---
Inserted {3,1,4,1,5,9,2,6} → size 7 (duplicate 1 removed)

--- 2. contains / count ---
contains(5): yes
contains(99): no
count(4): 1  count(1): 1

--- 3. insert and erase ---
insert(10): added
insert(5):  rejected (duplicate)
After erase(3): size=7, contains(3)=no, contains(10)=yes

--- 4. UnorderedSet<string> ---
Word set size: 4
contains("banana"): yes
erase("banana"): removed 1 element(s)

--- 5. clear ---
Before clear: empty=0 size=3
After clear:  empty=1 size=0

✓ Examples completed!
 * ============================================================================ */
