/**
 * @file unordered_map_example.cpp
 * @brief Runnable tour of UnorderedMap — key→value hash table with separate chaining.
 *
 * Demonstrates: operator[] insert/update, at(), contains/count, insert (no overwrite),
 * erase, initializer list, and clear.
 */

#include "unordered_map/unordered_map.hpp"
#include <iostream>
#include <string>
#include <stdexcept>

int main() {
    std::cout << "=== UnorderedMap Examples ===\n\n";

    // -------------------------------------------------------------------------
    // Section 1: operator[] — creates default value on first access
    // -------------------------------------------------------------------------
    std::cout << "--- 1. operator[] assignment ---\n";
    UnorderedMap<std::string, int> ages;
    ages["Alice"] = 30;
    ages["Bob"] = 25;
    ages["Charlie"] = 35;

    std::cout << "  Alice: " << ages["Alice"] << "\n";
    std::cout << "  Bob: " << ages["Bob"] << "\n";
    std::cout << "  Charlie: " << ages["Charlie"] << "\n";
    std::cout << "  Size: " << ages.size() << "\n";

    // -------------------------------------------------------------------------
    // Section 2: at() — throws on missing key (no silent insert)
    // -------------------------------------------------------------------------
    std::cout << "\n--- 2. at() vs missing key ---\n";
    try {
        std::cout << "  ages.at(\"Alice\") = " << ages.at("Alice") << "\n";
        ages.at("Nobody");
    } catch (const std::out_of_range& e) {
        std::cout << "  at(\"Nobody\") threw: " << e.what() << "\n";
    }

    // -------------------------------------------------------------------------
    // Section 3: contains / count / erase
    // -------------------------------------------------------------------------
    std::cout << "\n--- 3. contains, count, erase ---\n";
    std::cout << "  contains(\"Bob\"): " << (ages.contains("Bob") ? "yes" : "no") << "\n";
    std::cout << "  count(\"Bob\"): " << ages.count("Bob") << "\n";
    ages.erase("Bob");
    std::cout << "  After erase(\"Bob\"): size=" << ages.size()
              << ", contains Bob=" << (ages.contains("Bob") ? "yes" : "no") << "\n";

    // -------------------------------------------------------------------------
    // Section 4: insert — duplicate keys rejected (no overwrite)
    // -------------------------------------------------------------------------
    std::cout << "\n--- 4. insert (unique keys) ---\n";
    bool added = ages.insert({"Dave", 40});
    bool dup   = ages.insert({"Alice", 99});
    std::cout << "  insert Dave: " << (added ? "ok" : "fail") << "\n";
    std::cout << "  insert Alice again: " << (dup ? "ok" : "rejected") << "\n";
    std::cout << "  Alice still: " << ages["Alice"] << " (not 99)\n";

    // -------------------------------------------------------------------------
    // Section 5: Initializer list constructor
    // -------------------------------------------------------------------------
    std::cout << "\n--- 5. Initializer list ---\n";
    UnorderedMap<int, std::string> items = {{1, "one"}, {2, "two"}, {3, "three"}};
    std::cout << "  items[2] = " << items[2] << "\n";
    std::cout << "  items size: " << items.size() << "\n";

    // -------------------------------------------------------------------------
    // Section 6: clear
    // -------------------------------------------------------------------------
    std::cout << "\n--- 6. clear ---\n";
    items.clear();
    std::cout << "  After clear: empty=" << items.empty() << " size=" << items.size() << "\n";

    std::cout << "\n✓ Examples completed!\n";
    return 0;
}

/* ===== EXPECTED OUTPUT (sample run) ============================================
 * Auto-generated by running this program (see tests/README.md).
 * ----------------------------------------------------------------------------
=== UnorderedMap Examples ===

--- 1. operator[] assignment ---
  Alice: 30
  Bob: 25
  Charlie: 35
  Size: 3

--- 2. at() vs missing key ---
  ages.at("Alice") = 30
  at("Nobody") threw: UnorderedMap::at: key not found

--- 3. contains, count, erase ---
  contains("Bob"): yes
  count("Bob"): 1
  After erase("Bob"): size=2, contains Bob=no

--- 4. insert (unique keys) ---
  insert Dave: ok
  insert Alice again: rejected
  Alice still: 30 (not 99)

--- 5. Initializer list ---
  items[2] = two
  items size: 3

--- 6. clear ---
  After clear: empty=1 size=0

✓ Examples completed!
 * ============================================================================ */
